# Generated by Django 6.0.5 on 2026-05-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user.jpg', upload_to='profile_pic'),
        ),
    ]
