# Generated by Django 6.0.5 on 2026-05-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_item_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='https://img.freepik.com/premium-photo/top-view-empty-white-plate-meal-blank-plate-serving-food-composition-with-sun-dried-tomatoes-bruschetta-utensils-wooden-background-flat-lay_207126-3658.jpg', max_length=700, upload_to=''),
        ),
    ]
