# Generated by Django 6.0.5 on 2026-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_item_deleted_at_item_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://img.freepik.com/premium-photo/top-view-empty-white-plate-meal-blank-plate-serving-food-composition-with-sun-dried-tomatoes-bruschetta-utensils-wooden-background-flat-lay_207126-3658.jpg', max_length=700),
        ),
    ]
